### ISSUE TITLE
Oberservation period for statistics

### ISSUE THREAD

**Issue by elimei1** [EP1210/Budget_Fox#16]
# Card:

**Role:** User
**Goal:** Recieve statistics for specified observation period. 
**Reason:** The user wants to gain insight about his incomes and expenses for a self chosen period.

---

# Confirmation:

## Acceptance tests:

* UI (start and end date)

**Comment by michael-mezgo** [comment]
@elimei1 Reopened: https://github.com/EP1210/Budget_Fox/pull/38#issuecomment-2180196295

**Comment by michael-mezgo** [comment]
closed in #38 commit ff958f615640a8daf3ab963be3ea504992863744
