### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by michael-mezgo** [EP1210/Budget_Fox#39]
# Card:

**Role:** Developer
**Goal:** Readable code
**Reason:** Easy to understand code is important

---

# Confirmation:

## Acceptance tests:

* Application runs

**Comment by michael-mezgo** [comment]
# Households:

- [ ] HouseholdTransactionAddScreen & TransactionScreen -> One screen
- [ ] Use path variables more often to get rid of the "big" view model

**Comment by michael-mezgo** [comment]
# Input validaion

**Comment by EP1210** [comment]
# UserViewModel :scissors:

Split up the stateholders and functions into different ViewModels.

**Comment by EP1210** [comment]
See also this [discussion](https://github.com/EP1210/Budget_Fox/discussions/32).
