### ISSUE TITLE
Add expense

### ISSUE THREAD

**Issue by EP1210** [EP1210/Budget_Fox#4]
# Card:

**Role:** User
**Goal:** Specify the expense
**Reason:** The expense is needed to calculate the budget

---

# Confirmation:

## Acceptance tests:

* UI for adding the expense
* There can be multiple expenses
* The expenses are assigned to the specific user
* An expense consists of a date, an amount and a description

**Comment by michael-mezgo** [comment]
Solved with class "Transaction"
