### ISSUE TITLE
Statistic of incomes and expenses

### ISSUE THREAD

**Issue by EP1210** [EP1210/Budget_Fox#5]
# Card:

**Role:** User
**Goal:** Overview about incomes and expenses
**Reason:** The user needs to know how much was spent and received (on a monthly basis)

---

# Confirmation:

## Acceptance tests:

* UI for statistic
* Bar chart
   * One chart with two bars per month

**Comment by michael-mezgo** [comment]
@EP1210 
https://github.com/patrykandpatrick/vico
https://github.com/codeandtheory/YCharts

https://stackoverflow.com/a/76888821/21992499
